server:
  port: 8081
spring:
  main:
    banner-mode: off
  application:
    name: test
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: test
  artemis:
    user:  artemis
    password:  artemis
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: jetgrdr@gmail.com
    password: MTw2avYn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            required: true
  jms:
    pub-sub-domain: true
application:
  topic:
    audit: audit_queue